### ISSUE TITLE
您配置了servlet吗

### ISSUE THREAD

**Issue by Gundamass** [XXXHlown/Dormitory-Manage#1]
好像没有看到您的servlet是怎么配置的

**Comment by XXXHlown** [comment]
不太理解您的意思 如果是要看路由servlet的话 在文件夹 `src/jl/servlet`下配置

**Comment by XXXHlown** [comment]
> 好像没有看到您的servlet是怎么配置的

不太理解您的意思 如果是要看路由servlet的话 在文件夹 src/jl/servlet下配置

**Comment by Gundamass** [comment]
是这样的，如果要使用servlet不是应该在web.xml中配置一下的，老师是这么教我的。但是没能找到您的web.xml文件，所以我在想是否需要在web.xml中配置吗？如果有不对的地方请指正




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XXXHlown/Dormitory-Manage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XXXHlown/Dormitory-Manage] 您配置了servlet吗 (Issue #1)





  
好像没有看到您的servlet是怎么配置的
  
不太理解您的意思 如果是要看路由servlet的话 在文件夹 src/jl/servlet下配置

**Comment by XXXHlown** [comment]
> 是这样的，如果要使用servlet不是应该在web.xml中配置一下的，老师是这么教我的。但是没能找到您的web.xml文件，所以我在想是否需要在web.xml中配置吗？如果有不对的地方请指正
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "XXXHlown/Dormitory-Manage" ***@***.***&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 中午1:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [XXXHlown/Dormitory-Manage] 您配置了servlet吗 (Issue #1) 好像没有看到您的servlet是怎么配置的 不太理解您的意思 如果是要看路由servlet的话 在文件夹 src/jl/servlet下配置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您说的应该是tomcat的web.xml配置吧，这部分配置有许多本地化的内容不太适合分享，如果需要的话可以参考其他人的配置-

**Comment by Gundamass** [comment]
好的 感谢您的耐心解答

**Comment by Gundamass** [comment]
对不起 我今天是发现了您项目的jdbc版本和我的mysql版本不一致导致servlet报错 改成一致的版本就没问题了
